### ISSUE TITLE
Can not upload sound sample - no link in patch description.

### ISSUE THREAD

**Issue by syanenko** [zwippie/patch-library#5]
After creating Crave Udu drum patch I tried to upload sample and getting error (file was too large). Than after reducing the file size I created new patch with the same name and tried to upload one - no error, but no link to sound file too.

**Comment by zwippie** [comment]
@syanenko According to my logs the uploaded audio file was still too large. It should be less than 1 million bytes.

**Comment by syanenko** [comment]
HI, Arnold.

Thank you for your reply and for supporting this great resource. You are
right - uploading of mp3 of 83506 bites works fine.

Best regards,
Sergey.

**Comment by syanenko** [comment]
Hi, Arnold,

I also want to note, that it would be fine to have ability to leave some
comments about the patches, or likes at least.

Best regards,
Sergey.
