### ISSUE TITLE
FR: allow "blank" settings

### ISSUE THREAD

**Issue by masi** [zwippie/patch-library#6]
Not all knobs, sliders, LEDs, etc are used by every patch. Sometimes they cannot have an effect because of the patch, sometimes they are left for the user to change to taste.

For this cases it would IMHO convenient to remove the position indicator for knobs, sliders and switches, to show no LED when they are in radio-button style (eg filter mode of Neutron), to "grey- out" glowing buttons (eg all of Neutron's buttons).

The point is that a reader can see at one glance which UI elements of the synth are used by a patch. Just like in a patch sheet where markers are placed only at used elements.

**Comment by zwippie** [comment]
I've contemplated about this when I started the project, but settled for a default position for every knob.

There are so many possibilities when it comes to annotating a patch, like range indication for knobs, notes for individual knobs/buttons, etc. But that would make editing a patch much more complicated, require more images, more coding, perhaps more confusion for the reader... 

To summarize: I've opted for the 'realistic' approach.

(But thank you for your comments on improving the experience! 👍)
