### ISSUE TITLE
Suggestion for patch URLs: URLs match the patchname

### ISSUE THREAD

**Issue by m-r-m-s** [zwippie/patch-library#8]
Would it be possible to have user submitted patch URLs be dynamic, i.e. reflect the name of the patch? When you pull down a patch webpage to a mac OS desktop for example, the submitted patches are all identical: "Patch Libray.Webloc" (screen cap below).  

For example: Instead of having the patch name URL be: https://patch-library.net/patches/14d606a6-ea74-4fae-9879-a147b0c0c197
have it reflect the patches name: https://patch-library.net/patches/generative-noise-patch-by-sean-garland

Perhaps this is not possible with sites hosted on github? Thanks for your consideration

![Screen Shot 2020-02-03 at 12 43 03 PM](https://user-images.githubusercontent.com/16727232/73677187-b801b080-4683-11ea-9f1e-3e85d23cd164.png)

**Comment by zwippie** [comment]
Hi @m-r-m-s ,thank you for your suggestion. It looks like Safari is using the page title (header attribute) as the filename, not the URL? At least Chrome does so, cannot test on a mac until tomorrow.

But in the mean time I've added dynamic page titles to the website. I think it should be working in every browser now. Let me know how it's working out for you.

**Comment by m-r-m-s** [comment]
Hi @zwippie , thanks so much for the response. I tested on Firefox, Safari, and Chrome on macOS and the dynamic page titles are working - the patch names are reflected when you pull them down:
![Screen Shot 2020-02-04 at 9 18 57 AM](https://user-images.githubusercontent.com/16727232/73752699-6a428200-472f-11ea-981c-cd127c802141.png)
Thanks so much!
